export default [
  "Tyrion Lannister",
  "Jaime Lannister",
  "Cersei Lannister",
  "Daenerys Targaryen",
  "Jon Snow",
  "Petyr Baelish",
  "Jorah Mormont",
  "Sansa Stark",
  "Arya Stark",
  "Theon Greyjoy",
  "Bran Stark",
  "Sandor Clegane",
  "Joffrey Baratheon",
  "Catelyn Stark",
  "Robb Stark",
  "Ned Stark",
  "Robert Baratheon",
  "Viserys Targaryen",
  "Khal Drogo",
  "Varys",
  "Samwell Tarly",
  "Bronn",
  "Tywin Lannister",
  "Shae",
  "Jeor Mormont",
  "Gendry",
  "Tommen Baratheon",
  "Jaqen H'ghar",
  "Davos Seaworth",
  "Melisandre",
  "Margaery Tyrell",
  "Stannis Baratheon",
  "Ygritte",
  "Talisa Stark",
  "Brienne of Tarth",
  "Gilly",
  "Roose Bolton",
  "Tormund Giantsbane",
  "Ramsay Bolton",
  "Daario Naharis",
  "Missandei",
  "Ellaria Sand",
  "The High Sparrow",
  "Grand Maester Pycelle",
  "Loras Tyrell",
  "Hodor",
  "Gregor Clegane",
  "Meryn Trant",
  "Alliser Thorne",
  "Othell Yarwyck",
  "Kevan Lannister",
  "Lancel Lannister",
  "Myrcella Baratheon",
  "Rickon Stark",
  "Osha",
  "Janos Slynt",
  "Barristan Selmy",
  "Maester Aemon",
  "Grenn",
  "Hot Pie",
  "Pypar",
  "Rast",
  "Rodrik Cassel",
  "Maester Luwin",
  "Eddison Tollett",
  "Podrick Payne",
  "Yara Greyjoy",
  "Selyse Baratheon",
  "Olenna Tyrell",
  "Qyburn",
  "Grey Worm",
  "Meera Reed",
  "Shireen Baratheon",
  "Jojen Reed",
  "Mace Tyrell",
  "The Waif",
  "Bowen Marsh"
];